-- ============================================================================
-- 1. DROP TABLES (In reverse order of dependencies for clean re-runs)
-- ============================================================================
DROP TABLE Product_Warehouse CASCADE CONSTRAINTS;
DROP TABLE Reviews CASCADE CONSTRAINTS;
DROP TABLE Order_Items CASCADE CONSTRAINTS;
DROP TABLE Shipment CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;
DROP TABLE Coupon CASCADE CONSTRAINTS;
DROP TABLE Products CASCADE CONSTRAINTS;
DROP TABLE Warehouse CASCADE CONSTRAINTS;
DROP TABLE Categories CASCADE CONSTRAINTS;
DROP TABLE Sellers CASCADE CONSTRAINTS;
DROP TABLE Customers CASCADE CONSTRAINTS;
DROP TABLE Users CASCADE CONSTRAINTS;

-- ============================================================================
-- 2. CREATE ENTITY TABLES
-- ============================================================================

-- Base Table for ISA Inheritance
CREATE TABLE Users (
    UserID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Phone VARCHAR2(20) NOT NULL,
    DOB DATE NOT NULL,
    FirstName VARCHAR2(50) NOT NULL,
    LastName VARCHAR2(50) NOT NULL,
    Street VARCHAR2(100),
    City VARCHAR2(50),
    HouseNo VARCHAR2(20)
);

-- Sub-type: Customer
CREATE TABLE Customers (
    UserID INT PRIMARY KEY,
    JoinDate DATE DEFAULT SYSDATE NOT NULL,
    LoyaltyPoints INT DEFAULT 0,
    CONSTRAINT fk_cust_user_idx FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

-- Sub-type: Seller
CREATE TABLE Sellers (
    UserID INT PRIMARY KEY,
    ShopName VARCHAR2(100) UNIQUE NOT NULL,
    Ratings NUMBER(3,2) DEFAULT 0.0,
    CONSTRAINT fk_sell_user_idx FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

-- Categories with Unary/Recursive Relationship
CREATE TABLE Categories (
    CategoryID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CategoryName VARCHAR2(100) NOT NULL,
    ParentCategoryID INT,
    CONSTRAINT fk_cat_parent_idx FOREIGN KEY (ParentCategoryID) REFERENCES Categories(CategoryID) ON DELETE SET NULL
);

-- Warehouse Table
CREATE TABLE Warehouse (
    WarehouseID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Location VARCHAR2(150) NOT NULL,
    Capacity INT NOT NULL
);

-- Products Table (Renamed constraints here to eliminate ORA-02264)
CREATE TABLE Products (
    ProductID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SellerID INT NOT NULL,
    CategoryID INT NOT NULL,
    Name VARCHAR2(150) NOT NULL,
    Price NUMBER(10,2) NOT NULL,
    Taxes NUMBER(5,2) DEFAULT 0.0,
    SKU VARCHAR2(50) UNIQUE NOT NULL,
    Ratings NUMBER(3,2) DEFAULT 0.0,
    CONSTRAINT fk_prod_seller_unique FOREIGN KEY (SellerID) REFERENCES Sellers(UserID),
    CONSTRAINT fk_prod_cat_unique FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID)
);

-- Coupon Table
CREATE TABLE Coupon (
    CouponID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Code VARCHAR2(50) UNIQUE NOT NULL,
    ExpiryDate DATE NOT NULL
);

-- Orders Table
CREATE TABLE Orders (
    OrderID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID INT NOT NULL,
    OrderDate DATE DEFAULT SYSDATE NOT NULL,
    TotalAmount NUMBER(10,2) NOT NULL,
    CONSTRAINT fk_order_cust_idx FOREIGN KEY (CustomerID) REFERENCES Customers(UserID)
);

-- ============================================================================
-- 3. WEAK ENTITIES & WEAK RELATIONSHIPS
-- ============================================================================

-- Payment Weak Entity
CREATE TABLE Payment (
    PaymentID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID INT UNIQUE NOT NULL,
    Method VARCHAR2(50) NOT NULL,
    Amount NUMBER(10,2) NOT NULL,
    Status VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_pay_order_idx FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);

-- Shipment Weak Entity
CREATE TABLE Shipment (
    ShipmentID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID INT UNIQUE NOT NULL,
    ShipVia VARCHAR2(100) NOT NULL,
    Status VARCHAR2(50) NOT NULL,
    DeliverDate DATE,
    CONSTRAINT fk_ship_order_idx FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE
);

-- Order Items
CREATE TABLE Order_Items (
    OrderID INT,
    ItemID INT,
    ProductID INT NOT NULL,
    CouponID INT,
    Quantity INT NOT NULL,
    UnitPrice NUMBER(10,2) NOT NULL,
    PRIMARY KEY (OrderID, ItemID),
    CONSTRAINT fk_item_order_idx FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
    CONSTRAINT fk_item_prod_idx FOREIGN KEY (ProductID) REFERENCES Products(ProductID),
    CONSTRAINT fk_item_coupon_idx FOREIGN KEY (CouponID) REFERENCES Coupon(CouponID)
);

-- Reviews M:N Bridge Table
CREATE TABLE Reviews (
    CustomerID INT,
    ProductID INT,
    Rating INT CHECK (Rating BETWEEN 1 AND 5),
    Comments VARCHAR2(500),
    PRIMARY KEY (CustomerID, ProductID),
    CONSTRAINT fk_rev_cust_idx FOREIGN KEY (CustomerID) REFERENCES Customers(UserID) ON DELETE CASCADE,
    CONSTRAINT fk_rev_prod_idx FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON DELETE CASCADE
);

-- Product-Warehouse M:N Bridge Table
CREATE TABLE Product_Warehouse (
    ProductID INT,
    WarehouseID INT,
    AvailableQty INT DEFAULT 0,
    PRIMARY KEY (ProductID, WarehouseID),
    CONSTRAINT fk_pw_prod_idx FOREIGN KEY (ProductID) REFERENCES Products(ProductID) ON DELETE CASCADE,
    CONSTRAINT fk_pw_wh_idx FOREIGN KEY (WarehouseID) REFERENCES Warehouse(WarehouseID) ON DELETE CASCADE
);

-- ============================================================================
-- 4. INSERTING DUMMY DATA
-- ============================================================================
INSERT INTO Users (Email, Phone, DOB, FirstName, LastName, Street, City, HouseNo) VALUES ('alice@email.com', '1234567', TO_DATE('1995-05-12','YYYY-MM-DD'), 'Alice', 'Smith', 'Main St', 'Islamabad', '12');
INSERT INTO Users (Email, Phone, DOB, FirstName, LastName, Street, City, HouseNo) VALUES ('bob_shop@email.com', '7654321', TO_DATE('1988-10-22','YYYY-MM-DD'), 'Bob', 'Builder', 'Commercial Ln', 'Lahore', '45-B');

INSERT INTO Customers (UserID, LoyaltyPoints) VALUES (1, 150);
INSERT INTO Sellers (UserID, ShopName, Ratings) VALUES (2, 'Mega Sports Gear', 4.8);

INSERT INTO Categories (CategoryName, ParentCategoryID) VALUES ('Sports Gear', NULL);

-- This will now run perfectly since the table structural build succeeds!
INSERT INTO Products (SellerID, CategoryID, Name, Price, Taxes, SKU, Ratings) VALUES (2, 1, 'Pro Cricket Bat', 120.00, 5.00, 'CRIC-BAT-001', 4.5);

COMMIT;